
const AUTH_ACTION_TYPE = {
    CHECK_COOKIE: "CHECK_COOKIE",
    COOKIE_VALID: "COOKIE_VALID",
    COOKIE_INVALID: "COOKIE_INVALID",
    LOGIN: "LOGIN",
    LOGIN_VALID: "LOGIN_VALID",
    LOGIN_INVALID: "LOGIN_INVALID"
}