
const CATALOGUE_ACTION_TYPE = {
    FETCH_CATALOGUE_NAMES: "FETCH_CATALOGUE_NAMES",
    FETCH_CATALOGUE_NAMES_FAILED: "FETCH_CATALOGUE_NAMES_FAILED",
    RECEIVE_CATALOGUE_NAMES: "RECEIVE_CATALOGUE_NAMES",
    SELECT_CATALOGUE: "SELECT_CATALOGUE",
}

export default CATALOGUE_ACTION_TYPE