
const COLLECTION_ACTION_TYPE = {
    FETCH_COLLECTION_NAMES: "FETCH_COLLECTION_NAMES",
    FETCH_COLLECTION_NAMES_FAILED: "FETCH_COLLECTION_NAMES_FAILED",
    RECEIVE_COLLECTION_NAMES: "RECEIVE_COLLECTION_NAMES",
    SELECT_COLLECTION: "SELECT_COLLECTION",
}

export default COLLECTION_ACTION_TYPE