
const ITEM_ACTION_TYPE = {
    FETCH_ITEMS: "FETCH_ITEMS",
    FETCH_ITEMS_FAILED: "FETCH_ITEMS_FAILED",
    RECEIVE_ITEMS: "RECEIVE_ITEMS",
    SELECT_ITEM: "SELECT_ITEM",
}

export default ITEM_ACTION_TYPE